## What is an Array?

- An array is a data structure that stores a collection of elements (values or variables) of the same type in contiguous memory locations.
-  In Python, we typically use lists for similar functionality, but for numerical operations, we often use the array module or NumPy's ndarray.

## Why We Use Arrays

- Efficient storage: Arrays store elements compactly in memory
- Fast access: We can quickly access any element using its index
- Easy iteration: Simple to loop through all elements
- Mathematical operations: Great for numerical computations
- Ordered collection: Maintains the order of elements

## Where We Use Arrays

- Storing large amounts of similar data
- Mathematical computations (especially with NumPy)
- Image processing (images are arrays of pixels)
- Game development (storing game states, positions)
- Machine learning (datasets are often arrays)

## When We Use Arrays

- When you need to store many items of the same type
- When you need fast access to elements by position
- When you need to perform mathematical operations on the data
- When memory efficiency is important

In [ ]:
import numpy as np

In [ ]:
my_lst = [1,2,3,4,5]
arr=np.array(my_lst)

In [ ]:
type(arr)

In [ ]:
print(arr)

In [ ]:
arr.shape

In [ ]:
arr

In [20]:
# multinested array
my_lst1 = [1,2,3,4,5]
my_lst2 = [2,3,4,5,6]
my_lst3 = [9,7,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3])
# Single dimension array will open and close with single Bracket.
# Two dimenson arrat will open and close with 2 Brackets.
# Three dimenson arrat will open and close with 3 Brackets.

In [14]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [15]:
arr.shape

(3, 5)

In [16]:
arr.reshape(5,3) # when we are using reshape should keep note that the elements on shape should fix with reshape

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [17]:
arr.reshape(5,4) # cannot reshape array of size 15 into shape (5,4)

ValueError: cannot reshape array of size 15 into shape (5,4)

### Indexing

In [18]:
# Accessing the array element
arr = np.array([1,2,3,4,5,6,7,8,9])

In [19]:
arr[3]

np.int64(4)

In [21]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [ ]:
# Indexing in 2 dimension 
#(Row Indexing[each row will be consider as one index. e.g we have 3 rows in array so[0,1,2] is row index],
#(Column Indexing [] usual way each column is one index. e.g we have 5 columns in each row so[0,1,2,3,4] is column index)


In [22]:
# To Retrieve all columns.
arr[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [23]:
# To retrieve only first 2 rows
arr[0:2,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [24]:
# To retrieve first 2 rows and first 2 columns
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [25]:
# Inbuilt function arange
arr=np.arange(0,10)

In [26]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr=np.arange(0,10,step=2)

In [28]:
arr

array([0, 2, 4, 6, 8])

In [29]:
np.linspace(1,10,50) # mostly we use in Deep Learning

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [32]:
# Copy (creating an array to perform copy function)
arr = np.array([1,2,3,4,5,6,7,8,9])

In [35]:
# Copy () function and broadcasting
arr[3:] = 100 # if we want to print 100 from the 3rd index

In [36]:
arr

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [37]:
arr1=arr

In [38]:
arr1[3:] = 500 # if we want to print 500 from the 3rd index
print(arr)

[  1   2   3 500 500 500 500 500 500]


In [39]:
arr

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [40]:
# reference : when we updated arr1, automatically arr updated with those values.
# To avoid that we use copy command.
arr1 = arr.copy()

In [41]:
print(arr)
arr1[3:]=1000
print(arr1)

[  1   2   3 500 500 500 500 500 500]
[   1    2    3 1000 1000 1000 1000 1000 1000]


In [42]:
# Some Conditions very useful in Explaratory Data Analysis

val= 2 # Here I am creating a variable 
# we can perform various calculations like multiply, Division, Modulus with variable (e.g: arr*2, arr/2, arr%2,arr<2,arr>2)
arr<2  # It will check with each of the element in arr and provide result. In our example only 1 is <2, remaining are not matching.

array([ True, False, False, False, False, False, False, False, False])

In [43]:
# In the above example we are getting true or false . 
# If we want to get the exact values which are lessthan 2 use follow
arr[arr<2]

array([1])

In [44]:
# If we want to get the exact values which are lessthan 300 use follow
arr[arr<300]

array([1, 2, 3])

In [ ]:
# need to check from 20th minute to last in 4th class
# np.ones(1,dtype= int)
# np.random.rand(3,3)  () Values will change randomly after each execution
# arr_ex=np.random.randn(4,4) () Values will change randomly after each execution